columnSuffix: null
handle: photos
instructions: null
name: Photos
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:0e46e6a6-fe20-445c-b137-1cb5d794a4b9' # Photos
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:0e46e6a6-fe20-445c-b137-1cb5d794a4b9' # Photos
  restrictedLocationSubpath: null
  selectionLabel: 'Add photo'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:0e46e6a6-fe20-445c-b137-1cb5d794a4b9' # Photos
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
