dateModified: 1769474377
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:11840035-4d14-4256-98f8-92277616b0d6' # Portfolio
      tableAttributes:
        - 'field:f5c2dd32-dde2-41be-bc95-6ef40c9200b1' # Photos
        - 'field:9d860738-86c9-428f-9e65-92d65e552e73' # Date
        - 'field:d9925737-1ce3-46db-ab51-943d0d432d6a' # Materials
        - status
      type: native
email:
  fromEmail: kadenhendron@gmail.com
  fromName: halophile.science
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: assets
    type: craft\fs\Local
    url: /assets
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: assets/transforms
    type: craft\fs\Local
    url: /assets/transforms
meta:
  __names__:
    0e46e6a6-fe20-445c-b137-1cb5d794a4b9: Photos # Photos
    2faae296-354e-4a1f-8422-219648d70c4d: 'Portfolio Piece' # Portfolio Piece
    4b9b89e7-a505-4b83-ab72-1ff39f63c8bf: halophile.science # halophile.science
    6d12e4f6-3ac8-4685-ac99-bf9294ad6727: Paragraphs # Paragraphs
    8a90d9be-2ce1-480b-8ed5-3454448fcd97: Email # Email
    9d860738-86c9-428f-9e65-92d65e552e73: Date # Date
    0847cae1-7329-4bb0-a8c1-951e91ee0c08: 'Public Schema' # Public Schema
    936c995a-2981-4d76-b708-f342397dfbb7: Inquire # Inquire
    753212f1-1bdc-40de-93c3-6deed6911b5e: Info # Info
    843584ed-5237-4136-827c-ee49fe48db25: Inquire # Inquire
    11840035-4d14-4256-98f8-92277616b0d6: Portfolio # Portfolio
    ab881650-4ffc-4785-94f6-7980dd17014b: Simple # Simple
    b2ac8a68-d505-4592-a09a-550bdc8cd953: 'Square Grid Thumbnail' # Square Grid Thumbnail
    c96cd3bc-8609-4a8d-bb39-b06a121f5976: 'Single Line Rich Text' # Single Line Rich Text
    cd643bc4-4630-43ff-ad11-c36990eaeeb8: 'Single Line Rich Text' # Single Line Rich Text
    d9925737-1ce3-46db-ab51-943d0d432d6a: Materials # Materials
    f5c2dd32-dde2-41be-bc95-6ef40c9200b1: Photos # Photos
    fc05c3c3-c0ef-4b30-921d-47a30f4529fb: halophile.science # halophile.science
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: halophile.science
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
